# android
android.useAndroidX=true
android.nonTransitiveRClass=false

# gradle
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m

# LibGDX iOS/RoboVM target
gdxVersion=1.14.2
robovmVersion=2.3.23

#alternate band-aid for the `jvm target compatibility should be set to the same Java version` problem:
#kotlin.jvm.target.validation.mode = IGNORE
